name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chekout@v2

      - name: Sync and merge upstream repo
        uses: jsduenass/sync-docs@v0.alpha
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/phonkala/tswow-module-public-tests
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master
          # Branch to merge into downstream
          downstream_branch: master
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}
          
          
