name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Sync and merge upstream repo
        run: |
          git remote add upstream https://github.com/phonkala/tswow-module-public-tests.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
